apiVersion: apps/v1
kind: Deployment
metadata:
  name: floodit
  labels:
    app: floodit
spec:
  selector:
    matchLabels:
      app: floodit
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: floodit
    spec:
      containers:
        - name: floodit
          image: klmcwhirter/floodit
          ports:
            - containerPort: 80
